import type {
  LearnerProfile,
  Goal,
  Skill,
  Resource,
  Project,
  Assessment,
  AssessmentAttempt,
  AssessmentResult,
  LearningPath,
  Recommendation,
  ProgressData,
  Notification,
  ChatMessage,
  ChatConversation,
} from './index';

export const mockProfile: LearnerProfile = {
  user_id: 'usr_demo_01',
  name: 'Alex Rivera',
  current_role: 'Junior Frontend Developer',
  education: "Bachelor's in Computer Science",
  experience_level: 'intermediate',
  experience_years: 2,
  goals: ['Full-Stack Web & AI Application Architect'],
  target_outcome: 'Build production-ready full-stack applications with AI integrations and system design principles',
  timeline: '3–6 months (Recommended)',
  available_hours: 10,
  interests: ['System Architecture', 'Generative AI', 'High-Performance APIs', 'Cloud Deployment'],
  self_reported_skills: ['JavaScript', 'React', 'HTML/CSS', 'Git', 'Tailwind CSS'],
  verified_skills: ['JavaScript', 'React', 'HTML/CSS', 'Git'],
  learning_preferences: {
    style: 'project-based',
    pace: 'moderate',
  },
  learning_constraints: {
    constraints: ['Self-paced with hands-on projects', 'Focus on real-world architecture'],
  },
  motivation: 'Transition to a Senior Full-Stack role leading complex engineering systems.',
};

export const mockGoals: Goal[] = [
  {
    id: 'goal_01',
    title: 'Full-Stack Web & AI Application Architect',
    description: 'Master backend architectures, relational and vector databases, REST/GraphQL APIs, and AI integrations.',
    target_role: 'Full-Stack Engineer / AI Solutions Architect',
    timeline: '4 months',
    status: 'in_progress',
  },
];

export const mockSkills: Skill[] = [
  // Mastered / Already Know
  {
    id: 'sk_js',
    name: 'JavaScript & TypeScript',
    category: 'Programming languages',
    difficulty: 'Intermediate',
    description: 'Modern ES6+, async programming, closures, and static TypeScript typing.',
    self_score: 85,
    verified_score: 88,
    required_score: 80,
    confidence: 'High',
    status: 'Mastered',
    gap: 0,
    last_assessed: '2025-02-10',
  },
  {
    id: 'sk_react',
    name: 'React Ecosystem & State',
    category: 'Web frontend',
    difficulty: 'Intermediate',
    description: 'Component lifecycles, hooks, contexts, concurrent features, and performance.',
    self_score: 82,
    verified_score: 80,
    required_score: 75,
    confidence: 'High',
    status: 'Mastered',
    gap: 0,
    last_assessed: '2025-02-12',
  },
  {
    id: 'sk_git',
    name: 'Git & Version Control',
    category: 'Tools & practices',
    difficulty: 'Beginner',
    description: 'Branching strategies, rebase, merge conflict resolution, and CI/CD basics.',
    self_score: 90,
    verified_score: 92,
    required_score: 70,
    confidence: 'High',
    status: 'Mastered',
    gap: 0,
    last_assessed: '2025-02-05',
  },

  // Developing / In Progress
  {
    id: 'sk_sql',
    name: 'Relational Database Design & SQL',
    category: 'Data & databases',
    difficulty: 'Intermediate',
    description: 'PostgreSQL, query indexing, schema normalization, ACID transactions, and connection pooling.',
    self_score: 55,
    verified_score: 50,
    required_score: 80,
    confidence: 'Medium',
    status: 'Developing',
    gap: 30,
    last_assessed: '2025-02-18',
  },
  {
    id: 'sk_apis',
    name: 'RESTful API & Backend Services',
    category: 'Web backend',
    difficulty: 'Intermediate',
    description: 'HTTP protocol semantics, Node.js / Express / Django routing, middleware, and rate limiting.',
    self_score: 60,
    verified_score: 58,
    required_score: 85,
    confidence: 'Medium',
    status: 'Developing',
    gap: 27,
    last_assessed: '2025-02-20',
  },
  {
    id: 'sk_auth',
    name: 'Auth, Security & JWT/OAuth2',
    category: 'Security',
    difficulty: 'Intermediate',
    description: 'Secure session handling, token rotation, OAuth2 grant flows, and RBAC authorization.',
    self_score: 45,
    verified_score: 40,
    required_score: 80,
    confidence: 'Medium',
    status: 'Developing',
    gap: 40,
    last_assessed: '2025-02-15',
  },

  // Need to Learn / Priority Gaps
  {
    id: 'sk_sysdesign',
    name: 'System Design & Distributed Architecture',
    category: 'Backend & architecture',
    difficulty: 'Advanced',
    description: 'Caching with Redis, message queues (Kafka/RabbitMQ), load balancing, and horizontal scaling.',
    self_score: 20,
    verified_score: 15,
    required_score: 75,
    confidence: 'Low',
    status: 'Priority Gap',
    gap: 60,
    last_assessed: null,
  },
  {
    id: 'sk_rag',
    name: 'LLM Orchestration & RAG Pipelines',
    category: 'AI & machine learning',
    difficulty: 'Advanced',
    description: 'Vector databases, LangChain/LlamaIndex, embeddings, and prompt chaining.',
    self_score: 25,
    verified_score: 20,
    required_score: 70,
    confidence: 'Low',
    status: 'Priority Gap',
    gap: 50,
    last_assessed: null,
  },
  {
    id: 'sk_docker',
    name: 'Containerization & Cloud Deployment',
    category: 'DevOps & platform',
    difficulty: 'Intermediate',
    description: 'Docker multi-stage builds, container orchestration, reverse proxies (Nginx), and AWS deploy.',
    self_score: 30,
    verified_score: 25,
    required_score: 75,
    confidence: 'Low',
    status: 'Priority Gap',
    gap: 50,
    last_assessed: null,
  },
];

export const mockLearningPath: LearningPath = {
  id: 'lp_fullstack_ai_01',
  goal: 'Full-Stack Web & AI Application Architect',
  duration: '14 Weeks (10 hrs/week)',
  total_progress: 42,
  current_phase: 'phase_03',
  created_at: '2025-02-01',
  phases: [
    {
      id: 'phase_01',
      title: 'Phase 1: Advanced Frontend & TypeScript Architecture',
      objective: 'Master strict TypeScript patterns, design system components, and client-side performance optimization.',
      status: 'complete',
      progress: 100,
      skills: ['JavaScript & TypeScript', 'React Ecosystem & State', 'Tailwind CSS'],
      resources: ['Advanced TypeScript Patterns', 'React Concurrency Deep-Dive'],
      project: 'Reusable Component Library & State Dashboard',
      assessment: 'TypeScript & Modern React Architecture Benchmark',
      estimated_time: '3 weeks',
      order: 1,
    },
    {
      id: 'phase_02',
      title: 'Phase 2: Relational Databases & Schema Modeling',
      objective: 'Design normalized relational schemas, write optimized SQL queries, manage migrations, and implement indexing.',
      status: 'complete',
      progress: 100,
      skills: ['Relational Database Design & SQL', 'PostgreSQL', 'Query Optimization'],
      resources: ['PostgreSQL High Performance Guide', 'SQL Indexing & Execution Plans'],
      project: 'E-Commerce Database Schema & Performance Benchmark',
      assessment: 'SQL Proficiency & Schema Design Checkpoint',
      estimated_time: '3 weeks',
      order: 2,
    },
    {
      id: 'phase_03',
      title: 'Phase 3: Backend API Architecture & Security',
      objective: 'Build resilient REST APIs, implement JWT authentication with refresh token rotation, rate limiting, and RBAC.',
      status: 'current',
      progress: 45,
      skills: ['RESTful API & Backend Services', 'Auth, Security & JWT/OAuth2', 'WebSockets'],
      resources: ['Secure Authentication Architecture Guide', 'Building Real-time WebSockets with ASGI'],
      project: 'Production-Grade REST & WebSocket Gateway Service',
      assessment: 'API Security & Architecture Checkpoint',
      estimated_time: '3 weeks',
      order: 3,
    },
    {
      id: 'phase_04',
      title: 'Phase 4: Distributed Systems, Caching & Message Queues',
      objective: 'Implement Redis caching layers, async task queues, event-driven messaging, and system observability.',
      status: 'upcoming',
      progress: 0,
      skills: ['System Design & Distributed Architecture', 'Redis Caching', 'Message Queues'],
      resources: ['Distributed Caching Patterns', 'Designing Data-Intensive Applications Summary'],
      project: 'High-Throughput Asynchronous Task Processing Engine',
      assessment: 'Distributed Systems & Scalability Assessment',
      estimated_time: '3 weeks',
      order: 4,
    },
    {
      id: 'phase_05',
      title: 'Phase 5: AI Integration, Vector DBs & RAG Systems',
      objective: 'Connect LLM APIs, implement Retrieval-Augmented Generation (RAG) using vector search, and build intelligent assistants.',
      status: 'upcoming',
      progress: 0,
      skills: ['LLM Orchestration & RAG Pipelines', 'Vector Databases', 'Prompt Engineering'],
      resources: ['Production RAG Architecture', 'Vector Search & Embeddings in Practice'],
      project: 'AI-Powered Intelligent Search & Conversational Assistant',
      assessment: 'Generative AI & LLM Systems Evaluation',
      estimated_time: '2 weeks',
      order: 5,
    },
  ],
};

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec_01',
    resource_id: 'res_01',
    resource_title: 'Building Resilient REST APIs with Clean Architecture',
    source: 'Engineering Architecture Handbook',
    skill: 'RESTful API & Backend Services',
    score: 96,
    reason: 'Crucial for Milestone 3.2. Closes your 27% gap in backend route design and middleware pipelines.',
    difficulty: 'Intermediate',
    duration: '2.5 hours',
    type: 'Interactive Article & Code Walkthrough',
    status: 'accepted',
  },
  {
    id: 'rec_02',
    resource_id: 'res_02',
    resource_title: 'JWT Authentication & Refresh Token Rotation in Practice',
    source: 'Web Security Standards Lab',
    skill: 'Auth, Security & JWT/OAuth2',
    score: 94,
    reason: 'Addresses your highest priority security gap (40% delta) required before deploying Phase 3 project.',
    difficulty: 'Intermediate',
    duration: '3 hours',
    type: 'Video & Sandbox Workshop',
    status: 'pending',
  },
  {
    id: 'rec_03',
    resource_id: 'res_03',
    resource_title: 'High-Throughput Redis Caching & Invalidation Strategies',
    source: 'Distributed Systems Journal',
    skill: 'System Design & Distributed Architecture',
    score: 88,
    reason: 'Prerequisite for Phase 4. Prepares you for handling high-concurrency read replicas.',
    difficulty: 'Advanced',
    duration: '4 hours',
    type: 'Deep-Dive Article',
    status: 'pending',
  },
  {
    id: 'rec_04',
    resource_id: 'res_04',
    resource_title: 'Vector Databases & Embeddings for Full-Stack Developers',
    source: 'AI Engineering Academy',
    skill: 'LLM Orchestration & RAG Pipelines',
    score: 85,
    reason: 'Foundation reading for Phase 5 AI Assistant integration capstone.',
    difficulty: 'Intermediate',
    duration: '2 hours',
    type: 'Interactive Tutorial',
    status: 'pending',
  },
];

export const mockResources: Resource[] = [
  {
    id: 'res_01',
    title: 'Building Resilient REST APIs with Clean Architecture',
    source: 'Engineering Architecture Handbook',
    type: 'Article',
    difficulty: 'Intermediate',
    duration: '2.5 hours',
    url: 'https://example.com/resources/rest-clean-arch',
    skills: ['RESTful API & Backend Services', 'System Design'],
    rating: 4.9,
    reason: 'Directly addresses active Phase 3 milestone on clean service layers.',
    status: 'recommended',
    quality_score: 95,
  },
  {
    id: 'res_02',
    title: 'JWT Authentication & Refresh Token Rotation in Practice',
    source: 'Web Security Standards Lab',
    type: 'Workshop',
    difficulty: 'Intermediate',
    duration: '3 hours',
    url: 'https://example.com/resources/jwt-security-workshop',
    skills: ['Auth, Security & JWT/OAuth2'],
    rating: 4.8,
    reason: 'Covers essential token storage, CSRF mitigation, and replay defense.',
    status: 'recommended',
    quality_score: 93,
  },
  {
    id: 'res_03',
    title: 'PostgreSQL Indexing & Execution Plan Analysis',
    source: 'Database Performance Guild',
    type: 'Video series',
    difficulty: 'Intermediate',
    duration: '4.5 hours',
    url: 'https://example.com/resources/postgres-indexing',
    skills: ['Relational Database Design & SQL'],
    rating: 4.9,
    reason: 'Reinforces Phase 2 verified database design competencies.',
    status: 'completed',
    quality_score: 98,
  },
  {
    id: 'res_04',
    title: 'Distributed Caching Patterns with Redis',
    source: 'Distributed Systems Journal',
    type: 'Article',
    difficulty: 'Advanced',
    duration: '3 hours',
    url: 'https://example.com/resources/redis-caching-patterns',
    skills: ['System Design & Distributed Architecture'],
    rating: 4.7,
    reason: 'Upcoming preparation for Phase 4 high-concurrency scaling.',
    status: 'recommended',
    quality_score: 91,
  },
  {
    id: 'res_05',
    title: 'Vector Databases, Embeddings & RAG Architecture',
    source: 'AI Engineering Academy',
    type: 'Interactive',
    difficulty: 'Advanced',
    duration: '3.5 hours',
    url: 'https://example.com/resources/vector-rag-course',
    skills: ['LLM Orchestration & RAG Pipelines'],
    rating: 4.9,
    reason: 'Teaches vector similarity indexing for the final project capstone.',
    status: 'recommended',
    quality_score: 96,
  },
  {
    id: 'res_06',
    title: 'Docker & Multi-Stage Production Builds',
    source: 'DevOps Cloud Institute',
    type: 'Workshop',
    difficulty: 'Intermediate',
    duration: '2.5 hours',
    url: 'https://example.com/resources/docker-production',
    skills: ['Containerization & Cloud Deployment'],
    rating: 4.8,
    reason: 'Required for containerizing full-stack microservices before deployment.',
    status: 'recommended',
    quality_score: 92,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj_01',
    title: 'Design System & Typed Component Library',
    type: 'Frontend Architecture',
    description: 'Built a modular, accessible React design system with strict TypeScript, Storybook documentation, and automated linting.',
    skills: ['JavaScript & TypeScript', 'React Ecosystem & State'],
    estimated_time: '12 hours',
    status: 'completed',
    reason: 'Proves frontend state management and component engineering mastery.',
  },
  {
    id: 'proj_02',
    title: 'E-Commerce Normalized Schema & Query Benchmarking',
    type: 'Database Engineering',
    description: 'Designed a 3NF normalized schema with PostgreSQL, wrote complex analytical window queries, and added partial B-tree indices.',
    skills: ['Relational Database Design & SQL', 'PostgreSQL'],
    estimated_time: '14 hours',
    status: 'completed',
    reason: 'Validated data modeling and transaction isolation requirements.',
  },
  {
    id: 'proj_03',
    title: 'Production-Grade REST & WebSocket Gateway',
    type: 'Backend & Security',
    description: 'Build a secure API gateway featuring JWT authentication, token blacklisting in Redis, rate limiting, and bi-directional WebSocket push notifications.',
    skills: ['RESTful API & Backend Services', 'Auth, Security & JWT/OAuth2', 'WebSockets'],
    estimated_time: '18 hours',
    status: 'current',
    reason: 'The hero checkpoint for Phase 3: proves ability to architect secure, real-time backend systems.',
  },
  {
    id: 'proj_04',
    title: 'AI-Powered Document RAG Assistant with Vector Search',
    type: 'Generative AI & Cloud',
    description: 'Deploy a full-stack RAG pipeline connecting vector embeddings, hybrid semantic search, and streaming LLM responses with citations.',
    skills: ['LLM Orchestration & RAG Pipelines', 'Vector Databases', 'System Design'],
    estimated_time: '24 hours',
    status: 'recommended',
    reason: 'Capstones your full-stack journey into state-of-the-art AI application engineering.',
  },
];

export const mockProgress: ProgressData = {
  total_hours: 46.5,
  learning_streak: 12,
  completed_resources: 14,
  completed_projects: 2,
  completed_assessments: 3,
  overall_progress: 42,
  current_phase: 'Phase 3: Backend API Architecture & Security',
  average_score: 86,
  weekly_data: [
    { week: 'Week 1', hours: 9.5, score: 85, progress: 10 },
    { week: 'Week 2', hours: 11.0, score: 88, progress: 22 },
    { week: 'Week 3', hours: 10.5, score: 90, progress: 34 },
    { week: 'Week 4 (Current)', hours: 8.5, score: 84, progress: 42 },
  ],
  activity: [
    { day: 'Today', title: 'Studied JWT Token Rotation & Session Invalidation Patterns', duration: '1.5 hrs', completed: true },
    { day: 'Yesterday', title: 'Submitted API Gateway Route Handler Unit Tests', duration: '2.0 hrs', completed: true },
    { day: '3 days ago', title: 'Completed Database Schema Optimization Checkpoint', duration: '3.0 hrs', completed: true },
    { day: '5 days ago', title: 'Configured WebSocket Channel Layer with Redis', duration: '2.5 hrs', completed: true },
  ],
};

export const mockAssessments: Assessment[] = [
  {
    id: 'asmt_01',
    title: 'TypeScript & Modern React Architecture Benchmark',
    topic: 'Frontend Engineering',
    skill: 'JavaScript & TypeScript',
    difficulty: 'Intermediate',
    questions_count: 12,
    average_score: 90,
    status: 'completed',
    latest_attempt: {
      score: 92,
      date: '2025-02-08',
      status: 'passed',
    },
  },
  {
    id: 'asmt_02',
    title: 'Relational Database Design & Query Tuning Checkpoint',
    topic: 'Data & Databases',
    skill: 'Relational Database Design & SQL',
    difficulty: 'Intermediate',
    questions_count: 15,
    average_score: 85,
    status: 'completed',
    latest_attempt: {
      score: 88,
      date: '2025-02-18',
      status: 'passed',
    },
  },
  {
    id: 'asmt_03',
    title: 'API Security, JWT & Backend Architecture Evaluation',
    topic: 'Web Backend & Security',
    skill: 'RESTful API & Backend Services',
    difficulty: 'Intermediate',
    questions_count: 10,
    average_score: 75,
    status: 'available',
    latest_attempt: null,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif_01',
    title: 'Phase 3 Milestone Ready',
    body: 'You are ready to begin the REST & WebSocket Gateway Service checkpoint project.',
    type: 'milestone',
    read: false,
    created_at: '2025-02-24T10:30:00Z',
  },
  {
    id: 'notif_02',
    title: 'New AI Recommendation Added',
    body: 'Based on your goal, "JWT Authentication & Refresh Token Rotation" has been added to your shelf.',
    type: 'recommendation',
    read: false,
    created_at: '2025-02-23T14:15:00Z',
  },
  {
    id: 'notif_03',
    title: 'Learning Streak Milestone',
    body: 'Congratulations! You achieved a 12-day continuous learning streak.',
    type: 'achievement',
    read: true,
    created_at: '2025-02-22T09:00:00Z',
  },
];

export const mockConversations: ChatConversation[] = [
  {
    id: 'conv_default',
    title: 'Phase 3 Architecture Coaching',
    created_at: '2025-02-24T09:00:00Z',
    last_message: 'Why should I learn JWT rotation before deploying Phase 3?',
  },
];

export const mockChatHistory: ChatMessage[] = [
  {
    id: 'msg_01',
    from: 'assistant',
    text: "Hello Alex! I am your AI Learning Coach. Based on your current roadmap, you are in **Phase 3: Backend API Architecture & Security** targeting the *Full-Stack Web & AI Application Architect* destination. How can I guide you today?",
    timestamp: '10:00 AM',
  },
];
