import { useState, useEffect } from 'react';
import { Link } from 'wouter';
import {
  ArrowRight,
  Check,
  CheckCircle2,
  ChevronDown,
  Clock3,
  Compass,
  Download,
  Lock,
  Play,
  Sparkles,
  Target,
  Zap,
  BookOpen,
  BriefcaseBusiness,
  ShieldCheck,
  Circle,
  HelpCircle,
  Share2,
} from 'lucide-react';
import { learningPathService, type LearningPath, type LearningPathPhase } from '@/services/index';
import { SkeletonCard, ErrorState, EmptyState } from '@/components/states';
import { useToast } from '@/hooks/use-toast';

function ProgressBar({ value, color = '#176b65' }: { value: number; color?: string }) {
  return (
    <div className="h-2 w-full overflow-hidden rounded-full bg-[#e3e9e1]">
      <div
        className="h-full rounded-full transition-all duration-700 ease-out"
        style={{ width: `${Math.min(Math.max(value, 0), 100)}%`, background: color }}
      />
    </div>
  );
}

function StatusBadge({ status }: { status: 'complete' | 'current' | 'upcoming' | 'skipped' }) {
  if (status === 'complete') {
    return (
      <span className="inline-flex items-center gap-1 rounded-full bg-[#dceee4] px-2.5 py-1 text-[11px] font-bold text-[#176b65] border border-[#bcdcc8]">
        <CheckCircle2 size={12} /> Phase Completed & Verified
      </span>
    );
  }
  if (status === 'current') {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-full bg-[#fae9bb] px-3 py-1 text-[11px] font-bold text-[#93611a] border border-[#edd597] shadow-sm animate-pulse">
        <span className="size-2 rounded-full bg-[#d89c2c]" /> ACTIVE PHASE · YOU ARE HERE
      </span>
    );
  }
  return (
    <span className="inline-flex items-center gap-1 rounded-full bg-[#eef2ea] px-2.5 py-1 text-[11px] font-bold text-[#718079] border border-[#dce4da]">
      <Lock size={11} /> Locked Prerequisite
    </span>
  );
}

export default function LearningPath() {
  const { toast } = useToast();
  const [lp, setLp] = useState<LearningPath | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedPhaseId, setExpandedPhaseId] = useState<string>('phase_03');
  const [completedMilestones, setCompletedMilestones] = useState<string[]>(['ms_p1', 'ms_p2']);
  const [filter, setFilter] = useState<'all' | 'current' | 'completed' | 'upcoming'>('all');

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await learningPathService.getLearningPath();
      setLp(data);
      const cur = data.phases?.find((p) => p.status === 'current');
      if (cur) setExpandedPhaseId(cur.id);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Unable to load your learning path.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const toggleMilestone = (milestoneKey: string, milestoneTitle: string) => {
    const isNowDone = !completedMilestones.includes(milestoneKey);
    const updated = isNowDone
      ? [...completedMilestones, milestoneKey]
      : completedMilestones.filter((k) => k !== milestoneKey);

    setCompletedMilestones(updated);

    if (isNowDone) {
      toast({
        title: 'Milestone Completed! 🎉',
        description: `Verified milestone: "${milestoneTitle}". Pathway progress updated!`,
      });
    }
  };

  const handleExport = () => {
    if (!lp) return;
    const content = `# Personalized Learning Syllabus: ${lp.goal || 'Technical Roadmap'}
Generated by LearnPath AI · Adaptive Competency Engine

## Overview
- **Target Role Destination:** ${lp.goal || 'Full-Stack Web & AI Application Architect'}
- **Estimated Duration:** ${lp.duration || '14 Weeks'}
- **Weekly Study Commitment:** 10–12 Hours / Week
- **Current Verified Progress:** ${currentTotalProgress}%

---

## 5-Phase Sequential Curriculum Roadmap

${lp.phases
  .map(
    (p, i) => `### Phase ${i + 1}: ${p.title} [Status: ${p.status.toUpperCase()}]
- **Estimated Time:** ${p.estimated_time || '2–3 weeks'}
- **Objective:** ${p.objective || 'Master core architectural principles'}
- **Target Skills:** ${p.skills?.join(', ') || 'Core competencies'}
- **Checkpoint Project:** ${p.project || 'Phase Gateway Project'}
`
  )
  .join('\n---\n\n')}

---
*Exported from LearnPath AI — Adaptive Learning Platform*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LearnPath_${(lp.goal || 'Curriculum').replace(/[^a-zA-Z0-9]/g, '_')}_Syllabus.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: 'Syllabus Downloaded! 📄',
      description: 'Your personalized 5-phase learning curriculum has been saved as Markdown.',
    });
  };

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        <SkeletonCard rows={2} />
        <SkeletonCard rows={3} />
        <SkeletonCard rows={3} />
      </div>
    );
  }

  if (error) return <ErrorState title="Learning path unavailable" message={error} onRetry={load} />;
  if (!lp) {
    return (
      <EmptyState
        title="No learning path yet"
        description="Complete your onboarding to generate a personalized path."
        action={
          <Link href="/onboarding" className="rounded-xl bg-[#176b65] px-4 py-2 text-sm font-bold text-white">
            Start onboarding
          </Link>
        }
      />
    );
  }

  // Calculate live progress
  const completedPhasesCount = lp.phases.filter((p) => p.status === 'complete').length;
  const bonus = (completedMilestones.length - 2) * 5;
  const currentTotalProgress = Math.min(Math.max((lp.total_progress ?? 42) + bonus, 0), 100);

  const filteredPhases = lp.phases.filter((p) => {
    if (filter === 'all') return true;
    return p.status === filter;
  });

  return (
    <div className="space-y-8 animate-rise">
      {/* ─── Top Header & Destination ───────────────────────────────────────────── */}
      <div className="flex flex-wrap items-end justify-between gap-5 border-b border-[#dbe4da] pb-6">
        <div>
          <div className="flex items-center gap-2">
            <span className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[#b17820]">
              Personalized Curriculum Roadmap
            </span>
            <span className="text-[#c5cdc5]">/</span>
            <span className="inline-flex items-center gap-1 text-xs font-bold text-[#176b65]">
              <Compass size={13} /> Living Sequence Engine
            </span>
          </div>

          <h1 className="display mt-2 text-4xl font-bold tracking-[-.05em] text-[#20322f] md:text-5xl">
            The Road to {lp.goal}
          </h1>

          <p className="mt-3 max-w-3xl text-sm leading-6 text-[#718079]">
            A living sequence of 5 progressive phases designed around your existing frontend background, closing critical API and architecture gaps.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleExport}
            className="inline-flex items-center gap-2 rounded-xl border border-[#ccd8ce] bg-[#fbfaf5] px-4 py-2.5 text-xs font-bold text-[#36504a] shadow-sm hover:border-[#176b65] hover:text-[#176b65] transition"
          >
            <Download size={14} /> Export Syllabus
          </button>
          <Link
            href="/assistant"
            className="inline-flex items-center gap-2 rounded-xl bg-[#176b65] px-4 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-[#115a55] transition"
          >
            <Sparkles size={14} className="text-[#edbc55]" /> Ask Coach About Path
          </Link>
        </div>
      </div>

      {/* ─── Destination & Momentum Hero Banner ─────────────────────────────────── */}
      <section className="rounded-2xl border border-[#dbe4da] bg-gradient-to-br from-[#e4eee6] to-[#edf5f0] p-6 md:p-8 shadow-sm">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <div className="flex items-start gap-4">
            <span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#176b65] text-[#f7f5ed] shadow-sm">
              <Compass size={24} />
            </span>
            <div>
              <p className="font-mono text-[10px] font-bold uppercase tracking-wider text-[#718079]">
                Career Destination Target
              </p>
              <h2 className="display text-2xl md:text-3xl font-bold text-[#20322f]">{lp.goal}</h2>
              <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-[#61716c]">
                <span>Prerequisites Verified: <strong>JavaScript, React, Git</strong></span>
                <span>•</span>
                <span>Pace: <strong>10 hrs / week</strong></span>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-6 lg:gap-10 border-t lg:border-t-0 border-[#d0ded3] pt-4 lg:pt-0">
            {lp.duration && (
              <div>
                <p className="font-mono text-2xl font-bold text-[#176b65]">{lp.duration}</p>
                <p className="text-[10px] font-bold uppercase tracking-wider text-[#7c8b84]">Estimated Timeline</p>
              </div>
            )}
            <div>
              <p className="font-mono text-2xl font-bold text-[#176b65]">{completedPhasesCount} of {lp.phases.length}</p>
              <p className="text-[10px] font-bold uppercase tracking-wider text-[#7c8b84]">Phases Mastered</p>
            </div>
            <div>
              <p className="font-mono text-2xl font-bold text-[#176b65]">{currentTotalProgress}%</p>
              <p className="text-[10px] font-bold uppercase tracking-wider text-[#7c8b84]">Total Completion</p>
            </div>
          </div>
        </div>

        {/* Global Progress Line */}
        <div className="mt-6">
          <div className="flex justify-between text-xs font-bold text-[#40534d] mb-1.5">
            <span>Overall Curriculum Trajectory</span>
            <span className="font-mono">{currentTotalProgress}% Complete</span>
          </div>
          <ProgressBar value={currentTotalProgress} color="#176b65" />
        </div>
      </section>

      {/* ─── Filter Tabs ───────────────────────────────────────────────────────── */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e3e8e0] pb-4">
        <div className="flex flex-wrap items-center gap-2">
          {[
            { id: 'all', label: `All Phases (${lp.phases.length})` },
            { id: 'current', label: 'Active Phase (1)' },
            { id: 'completed', label: `Completed (${completedPhasesCount})` },
            { id: 'upcoming', label: `Upcoming (${lp.phases.length - completedPhasesCount - 1})` },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setFilter(tab.id as typeof filter)}
              className={`rounded-xl px-3.5 py-1.5 text-xs font-bold transition ${
                filter === tab.id
                  ? 'bg-[#20322f] text-white shadow-sm'
                  : 'bg-[#eef2ea] text-[#61716c] hover:bg-[#e2e8dc] hover:text-[#20322f]'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <span className="text-xs text-[#718079] font-mono">
          Interactive Pathway · Click to inspect checkpoints & proof
        </span>
      </div>

      {/* ─── Sequential Living Roadmap Nodes ────────────────────────────────────── */}
      <div className="space-y-6">
        {filteredPhases.map((phase: LearningPathPhase, i: number) => {
          const isExpanded = expandedPhaseId === phase.id;
          const isCurrent = phase.status === 'current';
          const isComplete = phase.status === 'complete';
          const isUpcoming = phase.status === 'upcoming';

          const phaseMilestonesList = [
            {
              id: `${phase.id}_m1`,
              title: `Core Conceptual Foundations: ${phase.skills?.slice(0, 2).join(', ') || 'Phase Fundamentals'}`,
              type: 'concept',
              duration: '4 hours',
              done: isComplete || completedMilestones.includes(`${phase.id}_m1`),
            },
            {
              id: `${phase.id}_m2`,
              title: `Hands-on Checkpoint Project: ${phase.project || 'Phase Applied Milestone'}`,
              type: 'project',
              duration: phase.estimated_time || '2 weeks',
              done: isComplete || completedMilestones.includes(`${phase.id}_m2`),
            },
            {
              id: `${phase.id}_m3`,
              title: `Diagnostic Evaluation: ${phase.assessment || 'Phase Competency Benchmark'}`,
              type: 'assessment',
              duration: '45 mins',
              done: isComplete || completedMilestones.includes(`${phase.id}_m3`),
            },
          ];

          return (
            <section
              key={phase.id}
              className={`relative overflow-hidden rounded-2xl border transition-all duration-200 ${
                isCurrent
                  ? 'border-[#edbc55] bg-[#fdfdf9] shadow-md ring-2 ring-[#edbc55]/30'
                  : isComplete
                  ? 'border-[#dbe4da] bg-[#fbfaf5] shadow-sm'
                  : 'border-[#dce4da] bg-[#f7f8f4] opacity-90'
              }`}
            >
              {/* Header Button */}
              <button
                onClick={() => setExpandedPhaseId(isExpanded ? '' : phase.id)}
                className="flex w-full items-start md:items-center gap-4 p-5 text-left md:p-6"
              >
                {/* Phase Number / Completion Icon */}
                <span
                  className={`grid size-11 shrink-0 place-items-center rounded-xl text-sm font-bold shadow-sm ${
                    isComplete
                      ? 'bg-[#176b65] text-[#f7f5ed]'
                      : isCurrent
                      ? 'bg-[#fae9bb] text-[#a66c15] border-2 border-[#edbc55]'
                      : 'bg-[#edf0eb] text-[#8b9891]'
                  }`}
                >
                  {isComplete ? <Check size={20} /> : isCurrent ? <Play size={17} fill="currentColor" /> : `0${i + 1}`}
                </span>

                {/* Phase Title & Subtitle */}
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2.5">
                    <h3 className={`display text-xl font-bold ${isCurrent ? 'text-[#176b65]' : 'text-[#20322f]'}`}>
                      {phase.title}
                    </h3>
                    <StatusBadge status={phase.status} />
                  </div>
                  {phase.objective && (
                    <p className="mt-1 text-xs md:text-sm text-[#718079] leading-relaxed line-clamp-2">
                      {phase.objective}
                    </p>
                  )}
                </div>

                {/* Progress Bar (Desktop) */}
                <div className="hidden min-w-[140px] md:block text-right">
                  <div className="flex justify-between text-xs font-mono font-bold mb-1">
                    <span className="text-[#718079]">Progress</span>
                    <span className={isCurrent ? 'text-[#a66c15]' : isComplete ? 'text-[#176b65]' : 'text-[#8b9891]'}>
                      {phase.progress}%
                    </span>
                  </div>
                  <ProgressBar
                    value={phase.progress}
                    color={isCurrent ? '#d89c2c' : isComplete ? '#176b65' : '#a0afa5'}
                  />
                  <span className="mt-1 block text-[10px] text-[#83918a] font-mono">
                    {phase.estimated_time || '3 weeks'}
                  </span>
                </div>

                {/* Chevron */}
                <span className="grid size-8 shrink-0 place-items-center rounded-xl bg-[#eef2ea] text-[#61716c]">
                  <ChevronDown
                    size={16}
                    className={`transition-transform duration-200 ${isExpanded ? 'rotate-180 text-[#176b65]' : ''}`}
                  />
                </span>
              </button>

              {/* Expandable Phase Details Drawer */}
              {isExpanded && (
                <div className="border-t border-[#e4e9e2] bg-[#f6f8f4] px-5 pb-7 pt-6 md:px-8 animate-fade">
                  {/* Prerequisite & Reasoning Banner */}
                  <div className="mb-6 rounded-xl bg-white p-4 border border-[#dbe4da] shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="space-y-1">
                      <span className="text-[10px] font-mono uppercase tracking-wider text-[#b17820] font-bold">
                        Phase Prerequisite Map
                      </span>
                      <p className="text-xs text-[#40534d]">
                        {i === 0
                          ? 'Starting baseline: Requires modern JavaScript & HTML/CSS fundamentals.'
                          : `Requires completion of Phase ${i}: ${lp.phases[i - 1]?.title}`}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <span className="inline-flex items-center gap-1 rounded-lg bg-[#e3eee7] px-2.5 py-1 text-xs font-bold text-[#176b65]">
                        <ShieldCheck size={13} /> {i <= 2 ? 'Prerequisites Satisfied ✓' : 'Pending Milestone Unlock'}
                      </span>
                    </div>
                  </div>

                  {/* 3-Column Breakdown: Skills, Milestones Checklist, Proof of Competence */}
                  <div className="grid gap-6 lg:grid-cols-3">
                    {/* Column 1: Skills Targeted */}
                    <div className="rounded-xl bg-white p-5 border border-[#dbe4da] space-y-3">
                      <div className="flex items-center gap-2 font-bold text-xs text-[#176b65]">
                        <Compass size={15} /> Skills Developed in This Phase
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {phase.skills?.map((s) => (
                          <span
                            key={s}
                            className="inline-flex rounded-lg bg-[#eef2ea] px-2.5 py-1 text-xs font-bold text-[#36504a]"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                      <p className="text-[11px] text-[#718079] leading-relaxed pt-2">
                        Targeting 80%+ role-readiness benchmarks across all listed concepts.
                      </p>
                    </div>

                    {/* Column 2: Interactive Milestone Checklist */}
                    <div className="rounded-xl bg-white p-5 border border-[#dbe4da] space-y-3">
                      <div className="flex items-center justify-between">
                        <span className="flex items-center gap-2 font-bold text-xs text-[#176b65]">
                          <Zap size={15} className="text-[#edbc55]" /> Phase Milestones
                        </span>
                        <span className="text-[10px] text-[#88958e] font-mono">Interactive</span>
                      </div>

                      <div className="space-y-2">
                        {phaseMilestonesList.map((ms) => (
                          <button
                            key={ms.id}
                            onClick={() => toggleMilestone(ms.id, ms.title)}
                            className={`w-full flex items-start gap-2.5 p-2 rounded-lg border text-left text-xs transition ${
                              ms.done
                                ? 'bg-[#edf5f0] border-[#ccd8ce] text-[#176b65]'
                                : 'bg-[#fafbf8] border-[#e3e8e0] text-[#40534d] hover:border-[#176b65]'
                            }`}
                          >
                            <span className="mt-0.5 shrink-0">
                              {ms.done ? (
                                <CheckCircle2 size={15} className="text-[#176b65]" />
                              ) : (
                                <Circle size={15} className="text-[#9aa7a0]" />
                              )}
                            </span>
                            <span className={`flex-1 font-semibold ${ms.done ? 'line-through opacity-80' : ''}`}>
                              {ms.title}
                            </span>
                          </button>
                        ))}
                      </div>
                    </div>

                    {/* Column 3: Proof of Progress & Capstone */}
                    <div className="rounded-xl bg-white p-5 border border-[#dbe4da] space-y-3 flex flex-col justify-between">
                      <div>
                        <div className="flex items-center gap-2 font-bold text-xs text-[#176b65]">
                          <BriefcaseBusiness size={15} /> Proof of Competence
                        </div>
                        {phase.project && (
                          <div className="mt-2.5">
                            <p className="text-[10px] uppercase font-mono font-bold text-[#88958e]">Capstone Project</p>
                            <p className="text-xs font-bold text-[#20322f] mt-0.5">{phase.project}</p>
                          </div>
                        )}
                        {phase.assessment && (
                          <div className="mt-2.5">
                            <p className="text-[10px] uppercase font-mono font-bold text-[#88958e]">Diagnostic Benchmark</p>
                            <p className="text-xs text-[#61716c] mt-0.5">{phase.assessment}</p>
                          </div>
                        )}
                      </div>

                      <div className="pt-3 border-t border-[#e8ede4] flex flex-wrap gap-2">
                        <Link
                          href={`/learning-path/${phase.id}`}
                          className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-xl bg-[#176b65] px-3 py-2 text-xs font-bold text-white hover:bg-[#115a55] transition shadow-sm"
                        >
                          <BookOpen size={13} /> {isCurrent ? 'Study Phase' : 'Phase Details'}
                        </Link>
                        <Link
                          href="/resources"
                          className="inline-flex items-center justify-center rounded-xl border border-[#ccd8ce] px-3 py-2 text-xs font-bold text-[#36504a] hover:border-[#176b65]"
                        >
                          Resources
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </section>
          );
        })}
      </div>
    </div>
  );
}
